---
# custom action - composite
name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them'
inputs:
  my_caching_param:
    description: Whether to cache dependecies or not.
    required: false
    default: 'true'
outputs:
  used-cache:
    description: Where the cached was used
    value: ${{ steps.install.outputs.cache_temp }}
runs:
  using: 'composite'
  steps:
    - name: Cache Dependencies
      if: inputs.my_caching_param == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: ${{ steps.cache.outputs.cache-hit != 'true' }} ||  input.my_caching_param != 'true'
      run: |
        npm ci
        echo "cache_temp=${{inputs.my_caching_param}}" >> $GITHUB_OUTPUT
      # need to specify shell
      shell: bash
