name: Artefacts
on: workflow_dispatch
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build website
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
    deploy-job:
      needs: build-job
      runs-on: ubuntu-latest
      steps:
        - name: Get build artifacts
          uses: actions/download-artifact@v4
          with:
            name: dist-files
        - name: Output contents
          run: ls
