name: First workflow
on: 
  - workflow_dispatch
  #- push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Multiple lines
        run: |
          echo "line 1"
          echo "line 2"
          uname -a
          pwd
      - name: Get Code
        uses: actions/checkout@v4
      - name: Show NPM version - before
        run: npm --version
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Show NPM version - after
        run: npm --version
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Print Goodbye
        run : echo "Done - bye!"
  deploy-job:
    needs: [test-job]
    runs-on: ubuntu-lastest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deloy to my website now!"
  output-job:
    needs: [test-job, deploy-job]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
