name: First workflow
on: 
  - workflow_dispatch
  - push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Multiple lines
        run: |
          echo "line 1"
          echo "line 2"
          uname -a
          pwd
      - name: Get Code
        uses: actions/checkout@v4
      - name: Show NPM version - before
        run: npm --version
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Show NPM version - after
        run: npm --version
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Print Goodbye
        run : echo "Done - bye!"
  deploy:
    needs: [test]
    runs-on: ubuntu-lastest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deloy to my website now!"