---
name: Matrix workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-job:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
