---
name: Reusable Deploy
on:
  workflow_call:
    inputs:
      my-artifact-name:
        description: The name of the deployable artifact files
        require: false
        default: dist
        type: string
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "just to demo reusable workflow"
